import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { FileJson, FileText, Download, Hash, ShieldCheck, UserCheck, Loader2, AlertCircle, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

interface EvidencePackProps {
  evidenceId: string;
}

// Database Evidence type from API (updated to match new schema)
interface DbEvidence {
  id: number;
  evidenceId: string;
  decisionId: string;
  actorId: number;
  actorName: string;
  actorRole: string;
  action: "APPROVED" | "REJECTED" | "ESCALATED";
  justification: string;
  policySnapshot: string;
  policyText: string | null;
  merkleHash: string;
  executionRef: string | null;
  executionChannel: string | null;
  executionAmount: string | null;
  executionCurrency: string | null;
  executionStatus: string | null;
  executionTimestamp: Date | null;
  dualControlRequired: number | null;
  escalationTriggered: number | null;
  overrideApplied: number | null;
  createdAt: Date;
}

export function EvidencePack({ evidenceId }: EvidencePackProps) {
  const { data: evidence, isLoading, error } = trpc.evidence.get.useQuery(
    { evidenceId },
    { enabled: !!evidenceId }
  );

  /**
   * Generate a regulator-grade 4-page PDF Evidence Pack
   * Layout follows the handover specification exactly
   */
  const generatePDF = (evidence: DbEvidence) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    const addFooter = (pageNum: number) => {
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(128, 128, 128);
      doc.text(`Generated by Turing | ${evidence.evidenceId} | ${new Date().toISOString()}`, pageWidth / 2, pageHeight - 10, { align: "center" });
      doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 10);
      doc.setTextColor(0, 0, 0);
    };

    const drawDivider = (y: number) => {
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.3);
      doc.line(20, y, pageWidth - 20, y);
    };

    // ============================================
    // PAGE 1 — DECISION SUMMARY
    // ============================================
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("TURING DECISION EVIDENCE PACK", pageWidth / 2, 25, { align: "center" });
    drawDivider(30);

    let y = 45;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Decision ID:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(evidence.decisionId, 70, y);
    
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text("Decision Type:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(evidence.action === "APPROVED" ? "Payment Approval" : evidence.action, 70, y);
    
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text("Status:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(evidence.action, 70, y);
    
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text("Risk Classification:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text("MEDIUM", 70, y);

    y += 20;
    drawDivider(y);
    y += 15;
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("DECISION CONTEXT", 20, y);
    
    y += 12;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Action:", 20, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    const actionText = evidence.executionAmount 
      ? `Payment of ${evidence.executionAmount} to External Beneficiary`
      : `Decision ${evidence.decisionId} - ${evidence.action}`;
    doc.text(actionText, 20, y);
    
    y += 12;
    doc.setFont("helvetica", "bold");
    doc.text("Triggered Policy:", 20, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.text(evidence.policySnapshot, 20, y);
    
    if (evidence.policyText) {
      y += 7;
      const policyLines = doc.splitTextToSize(evidence.policyText, pageWidth - 40);
      doc.text(policyLines.slice(0, 3), 20, y);
      y += policyLines.slice(0, 3).length * 5;
    }

    y += 20;
    drawDivider(y);
    y += 15;
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("DECISION OUTCOME", 20, y);
    
    y += 12;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Outcome:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(evidence.action, 70, y);
    
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Justification:", 20, y);
    y += 7;
    doc.setFont("helvetica", "italic");
    const justLines = doc.splitTextToSize(evidence.justification, pageWidth - 40);
    doc.text(justLines, 20, y);

    addFooter(1);

    // ============================================
    // PAGE 2 — AUTHORITY & ACCOUNTABILITY
    // ============================================
    doc.addPage();
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("AUTHORITY CHAIN", 20, 25);
    drawDivider(30);
    
    y = 45;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Role:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(evidence.actorRole, 70, y);
    
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text("Actor:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(evidence.actorName, 70, y);
    
    y += 8;
    doc.setFont("helvetica", "bold");
    doc.text("Timestamp:", 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(new Date(evidence.createdAt).toISOString(), 70, y);
    
    y += 12;
    doc.setFont("helvetica", "bold");
    doc.text("Authority Basis:", 20, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.text(`Delegated authority under ${evidence.policySnapshot.split(" ")[0]}`, 20, y);

    y += 25;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("DECISION CONTROLS", 20, y);
    drawDivider(y + 5);
    
    y += 20;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`• Dual control: ${evidence.dualControlRequired ? "REQUIRED" : "NOT REQUIRED"}`, 20, y);
    y += 8;
    doc.text(`• Escalation: ${evidence.escalationTriggered ? "TRIGGERED" : "NOT TRIGGERED"}`, 20, y);
    y += 8;
    doc.text(`• Override: ${evidence.overrideApplied ? "YES" : "NO"}`, 20, y);

    addFooter(2);

    // ============================================
    // PAGE 3 — EXECUTION & LEDGER REFERENCE
    // ============================================
    doc.addPage();
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTION RECORD", 20, 25);
    drawDivider(30);
    
    y = 45;
    doc.setFontSize(10);
    
    if (evidence.executionRef) {
      doc.setFont("helvetica", "bold");
      doc.text("Execution Reference:", 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(evidence.executionRef, 80, y);
      y += 8;
    }
    
    if (evidence.executionChannel) {
      doc.setFont("helvetica", "bold");
      doc.text("Channel:", 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(evidence.executionChannel, 80, y);
      y += 8;
    }
    
    if (evidence.executionAmount) {
      doc.setFont("helvetica", "bold");
      doc.text("Amount:", 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(evidence.executionAmount, 80, y);
      y += 8;
    }
    
    if (evidence.executionCurrency) {
      doc.setFont("helvetica", "bold");
      doc.text("Currency:", 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(evidence.executionCurrency, 80, y);
      y += 8;
    }
    
    if (evidence.executionStatus) {
      doc.setFont("helvetica", "bold");
      doc.text("Execution Status:", 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(evidence.executionStatus, 80, y);
      y += 8;
    }
    
    if (evidence.executionTimestamp) {
      doc.setFont("helvetica", "bold");
      doc.text("Execution Timestamp:", 20, y);
      doc.setFont("helvetica", "normal");
      doc.text(new Date(evidence.executionTimestamp).toISOString(), 80, y);
    }

    addFooter(3);

    // ============================================
    // PAGE 4 — INTEGRITY & VERIFICATION
    // ============================================
    doc.addPage();
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("INTEGRITY VERIFICATION", 20, 25);
    drawDivider(30);
    
    y = 45;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Evidence Hash (SHA-256):", 20, y);
    
    y += 10;
    doc.setFontSize(8);
    doc.setFont("courier", "normal");
    const hashLines = doc.splitTextToSize(evidence.merkleHash, pageWidth - 40);
    doc.text(hashLines, 20, y);
    
    y += hashLines.length * 4 + 20;
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    const disclaimer = "This evidence pack is an immutable record generated by the Turing Decision System. Any modification to this document will invalidate the cryptographic hash.";
    const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - 40);
    doc.text(disclaimerLines, 20, y);

    addFooter(4);

    // Save
    doc.save(`${evidence.evidenceId}.pdf`);
    toast.success("PDF Generated", { description: `Regulator-grade evidence pack saved as ${evidence.evidenceId}.pdf` });
  };

  const downloadJSON = (evidence: DbEvidence) => {
    const jsonData = JSON.stringify(evidence, null, 2);
    const blob = new Blob([jsonData], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${evidence.evidenceId}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("JSON Exported", { description: `Saved as ${evidence.evidenceId}.json` });
  };

  const downloadCSV = (evidence: DbEvidence) => {
    const headers = ["Field", "Value"];
    const rows = [
      ["Evidence ID", evidence.evidenceId],
      ["Decision ID", evidence.decisionId],
      ["Actor", `${evidence.actorName} (${evidence.actorRole})`],
      ["Action", evidence.action],
      ["Timestamp", new Date(evidence.createdAt).toISOString()],
      ["Policy Version", evidence.policySnapshot],
      ["Justification", evidence.justification],
      ["Merkle Hash", evidence.merkleHash],
      ["Execution Reference", evidence.executionRef || "N/A"],
      ["Execution Channel", evidence.executionChannel || "N/A"],
      ["Execution Amount", evidence.executionAmount || "N/A"],
      ["Execution Status", evidence.executionStatus || "N/A"],
      ["Dual Control Required", evidence.dualControlRequired ? "Yes" : "No"],
      ["Escalation Triggered", evidence.escalationTriggered ? "Yes" : "No"],
    ];
    
    const csvContent = [
      headers.join(","),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(","))
    ].join("\n");
    
    const blob = new Blob([csvContent], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${evidence.evidenceId}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("CSV Exported", { description: `Saved as ${evidence.evidenceId}.csv` });
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-[50vh]">
        <Loader2 className="h-8 w-8 animate-spin text-orange-500" />
      </div>
    );
  }

  if (error || !evidence) {
    return (
      <div className="flex flex-col items-center justify-center h-[50vh] text-zinc-500">
        <h2 className="text-xl font-bold text-white mb-2">Evidence Pack Not Found</h2>
        <p>The requested evidence ID does not exist.</p>
      </div>
    );
  }

  const actionColors: Record<string, string> = {
    APPROVED: "bg-emerald-900/50 text-emerald-400 border-emerald-800",
    REJECTED: "bg-rose-900/50 text-rose-400 border-rose-800",
    ESCALATED: "bg-amber-900/50 text-amber-400 border-amber-800",
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <ShieldCheck className="h-6 w-6 text-emerald-500" />
            Evidence Pack
          </h1>
          <p className="text-zinc-400 text-sm mt-1 font-mono">{evidence.evidenceId}</p>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            className="border-zinc-700 text-zinc-300 hover:text-white"
            onClick={() => generatePDF(evidence)}
          >
            <FileText className="mr-2 h-4 w-4" /> PDF
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            className="border-zinc-700 text-zinc-300 hover:text-white"
            onClick={() => downloadJSON(evidence)}
          >
            <FileJson className="mr-2 h-4 w-4" /> JSON
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            className="border-zinc-700 text-zinc-300 hover:text-white"
            onClick={() => downloadCSV(evidence)}
          >
            <Download className="mr-2 h-4 w-4" /> CSV
          </Button>
        </div>
      </div>

      <Card className="bg-zinc-900 border-zinc-800 p-8 space-y-8">
        {/* Chain of Custody */}
        <section>
          <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-4 border-b border-zinc-800 pb-2">
            Chain of Custody
          </h3>
          <div className="grid grid-cols-2 gap-8">
            <div>
              <div className="text-xs text-zinc-500 mb-1">Actor</div>
              <div className="flex items-center gap-2 text-white font-medium">
                <UserCheck className="h-4 w-4 text-zinc-400" />
                {evidence.actorName} ({evidence.actorRole})
              </div>
            </div>
            <div>
              <div className="text-xs text-zinc-500 mb-1">Timestamp</div>
              <div className="text-white font-mono">{new Date(evidence.createdAt).toUTCString()}</div>
            </div>
            <div>
              <div className="text-xs text-zinc-500 mb-1">Action Taken</div>
              <Badge className={`${actionColors[evidence.action]} hover:opacity-80`}>
                {evidence.action}
              </Badge>
            </div>
            <div>
              <div className="text-xs text-zinc-500 mb-1">Policy Version</div>
              <div className="text-white font-mono">{evidence.policySnapshot}</div>
            </div>
          </div>
        </section>

        {/* Decision Controls */}
        <section>
          <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-4 border-b border-zinc-800 pb-2">
            Decision Controls
          </h3>
          <div className="grid grid-cols-3 gap-4">
            <div className="flex items-center gap-2">
              {evidence.dualControlRequired ? (
                <AlertCircle className="h-4 w-4 text-amber-500" />
              ) : (
                <CheckCircle2 className="h-4 w-4 text-zinc-500" />
              )}
              <span className="text-sm text-zinc-300">
                Dual Control: {evidence.dualControlRequired ? "Required" : "Not Required"}
              </span>
            </div>
            <div className="flex items-center gap-2">
              {evidence.escalationTriggered ? (
                <AlertCircle className="h-4 w-4 text-amber-500" />
              ) : (
                <CheckCircle2 className="h-4 w-4 text-zinc-500" />
              )}
              <span className="text-sm text-zinc-300">
                Escalation: {evidence.escalationTriggered ? "Triggered" : "Not Triggered"}
              </span>
            </div>
            <div className="flex items-center gap-2">
              {evidence.overrideApplied ? (
                <AlertCircle className="h-4 w-4 text-rose-500" />
              ) : (
                <CheckCircle2 className="h-4 w-4 text-zinc-500" />
              )}
              <span className="text-sm text-zinc-300">
                Override: {evidence.overrideApplied ? "Applied" : "No"}
              </span>
            </div>
          </div>
        </section>

        {/* Justification */}
        <section>
          <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-4 border-b border-zinc-800 pb-2">
            Human Justification
          </h3>
          <div className="bg-zinc-950/50 p-4 rounded border border-zinc-800 text-zinc-300 italic font-serif">
            "{evidence.justification}"
          </div>
        </section>

        {/* Execution Record */}
        {evidence.executionRef && (
          <section>
            <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-4 border-b border-zinc-800 pb-2">
              Execution Record
            </h3>
            <div className="grid grid-cols-2 gap-6">
              <div>
                <div className="text-xs text-zinc-500 mb-1">Execution Reference</div>
                <div className="text-orange-500 font-mono">{evidence.executionRef}</div>
              </div>
              {evidence.executionChannel && (
                <div>
                  <div className="text-xs text-zinc-500 mb-1">Channel</div>
                  <div className="text-white">{evidence.executionChannel}</div>
                </div>
              )}
              {evidence.executionAmount && (
                <div>
                  <div className="text-xs text-zinc-500 mb-1">Amount</div>
                  <div className="text-white font-mono">{evidence.executionAmount} {evidence.executionCurrency}</div>
                </div>
              )}
              {evidence.executionStatus && (
                <div>
                  <div className="text-xs text-zinc-500 mb-1">Status</div>
                  <Badge className="bg-emerald-900/50 text-emerald-400 border-emerald-800">
                    {evidence.executionStatus}
                  </Badge>
                </div>
              )}
            </div>
          </section>
        )}

        {/* Cryptographic Proof */}
        <section>
          <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-4 border-b border-zinc-800 pb-2">
            Cryptographic Proof
          </h3>
          <div className="space-y-4">
            <div>
              <div className="text-xs text-zinc-500 mb-1">Evidence Hash (SHA-256)</div>
              <div className="flex items-center gap-2 font-mono text-xs text-zinc-400 bg-black p-2 rounded border border-zinc-800 break-all">
                <Hash className="h-3 w-3 shrink-0" />
                {evidence.merkleHash}
              </div>
            </div>
          </div>
        </section>
      </Card>
    </div>
  );
}
